---
# tasks file for ubuntuvm
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ rg }}-rg"
    name: "{{ vm_name }}"
    vm_size: Standard_B1s
    #availability_set: "{{ rg }}-as"
    #managed_disk_type: Standard_LRS
    admin_username: "{{ admin_username }}" 
    ssh_password_enabled: false
    ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key_data }}" 
    network_interfaces: "{{ vm_name }}-nic00"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: '18.04-LTS'
      version: latest
