---
# tasks file for panfwpaip
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ vmname }}-rg"
    allocation_method: Static
    sku: Standard
    name: "{{ vmname }}-mgmt-paip"
  register: output_ip_address
- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ vmname }}-rg"
    allocation_method: Static
    sku: Standard
    name: "{{ vmname }}-internet-paip"
  register: output_ip_address
- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."

