---
# tasks file for nic
- name: Create a network with mutilple ip configurations
  azure_rm_networkinterface:
    name: "{{ vm_name }}-nic00"
    resource_group: "{{ rg }}-rg"
    subnet_name: "{{ rg }}-subnet"
    virtual_network_name: "{{ rg }}-vnet"
    security_group_name: "{{ rg }}-nsg"
    ip_configurations:
      - name: ipconfig1
        public_ip_address_name: "{{ vm_name }}-paip"
        primary: True
        private_ip_allocation_method: Static
        private_ip_address: "{{ address_pvtip }}"
