---
# tasks file for nsg
- name: Create Network Security Group that allows all
  azure_rm_securitygroup:
    resource_group: "{{ vmname }}-rg"
    name: "{{ vmname }}-nsg"
    rules:
      - name: Allow-all
        protocol: Tcp
        destination_port_range: '*'
        access: Allow
        priority: 1001
        direction: Inbound
