# Creation of Pan firewall VM 01
- hosts: localhost
  vars:
    vmname: panfw01
    location: eastus
    mgmt_pvtip: 10.1.0.4
    internet_pvtip: 10.1.1.4
    intranet_pvtip: 10.1.2.4
    admin_username: azureuser
    ssh_key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0QdzuAeq5lSS5GvMommPcUp4WmnJ96XL93SkXrgUKi+EzRmAREq1q3ZAVK3vyGda5lsUki4icms/8n3bhEPX6OWSBLuXwkeGaQ6lvOIzcKTd0fySOapXwws/5YnliJjIZuNkJun1joVWjO1XlKdZpNsYm0peuYmu8sJakDE7Kclo7JGmolCg4L3GA4frXQv2rkNr9nugLp6eULL78BE7XNn/5OF+G4T88keHKJEZpHLQouwJDKnj48KJQAorgt7Ol9SUNWOB+Uq3A8HO4SqiXvF8PXuTd8LkSzXQ1u6PWfERwYAW3DYmXPQmiwsedyGWZMRd+euhX4WOA+z549zcJ
  tasks:
      - include_role:
           name: panfwpaip
      - include_role:
           name: nsg           
      - include_role:
           name: panfw
      - include_role:
           name: panfwvm

#### Creation of PAN  Firewall VM 02
      
- hosts: localhost
  vars:
    vmname: panfw02
    location: eastus
    mgmt_pvtip: 10.3.0.4
    internet_pvtip: 10.3.1.4
    intranet_pvtip: 10.3.2.4
    admin_username: azureuser
    ssh_key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0QdzuAeq5lSS5GvMommPcUp4WmnJ96XL93SkXrgUKi+EzRmAREq1q3ZAVK3vyGda5lsUki4icms/8n3bhEPX6OWSBLuXwkeGaQ6lvOIzcKTd0fySOapXwws/5YnliJjIZuNkJun1joVWjO1XlKdZpNsYm0peuYmu8sJakDE7Kclo7JGmolCg4L3GA4frXQv2rkNr9nugLp6eULL78BE7XNn/5OF+G4T88keHKJEZpHLQouwJDKnj48KJQAorgt7Ol9SUNWOB+Uq3A8HO4SqiXvF8PXuTd8LkSzXQ1u6PWfERwYAW3DYmXPQmiwsedyGWZMRd+euhX4WOA+z549zcJ
  tasks:
      - include_role:
           name: panfwpaip
      - include_role:
           name: nsg
      - include_role:
           name: panfw
      - include_role:
           name: panfwvm
