---
# tasks file for aset
- name: Create an availability set with advanced options
  azure_rm_availabilityset:
    name: "{{ vmname }}-as"
    location: "{{ location }}"
    resource_group: "{{ vmname }}-rg"
    platform_update_domain_count: 5
    platform_fault_domain_count: 3
    sku: Aligned
