---
# tasks file for web-apache
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ rg }}-rg"
    name: "{{ vm_name }}"
    vm_size: Standard_B1s
    availability_set: "{{ rg }}-as"
    admin_username: "{{ admin_username }}" 
    ssh_password_enabled: false
    ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key_data }}" 
    network_interfaces: "{{ nic_name }}"
    image: "{{ image_name }}"
